### ISSUE TITLE
header 스크롤 이벤트 반응형 

### ISSUE THREAD

**Issue by whl5105** [ad-earth/client-v2.0#45]
https://user-images.githubusercontent.com/73993670/229270806-8320a8f8-7ce9-441d-b415-d759431fcf7f.mov

 모바일 반응형 스크롤시   header 값이 사라지는데 혹시 의도하신 걸까요 아니면 이슈 일까요?

**Comment by damiiya** [comment]
스크롤 이벤트는 viewport 990 이상에서만 보이도록 설정되어 있습니다! (의도된 설정입니다😀)
